export const ATTEMPT_LOGIN = 'ATTEMPT LOGIN';
export const LOGIN_SUCCESS = 'LOGIN SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const ATTEMPT_LOGOUT = 'ATTEMPT_LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';