export const RETRIEVE_STATIONS = "RETRIEVE_STATIONS";
export const GOT_STATIONS = "GOT_STATIONS";
export const FAILED_GET_STATIONS = "FAILED_GET_STATIONS";
export const SORT_STATIONS = "SORT_STATIONS";
export const SELECT_STATION = "SELECT_STATION"